# Generated by Django 4.1.3 on 2022-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kekw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='tag',
            field=models.CharField(default='lofi', max_length=100),
            preserve_default=False,
        ),
    ]
