# Generated by Django 4.1.3 on 2022-12-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kekw', '0003_radiouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiouser',
            name='radios',
        ),
        migrations.AddField(
            model_name='radiouser',
            name='img',
            field=models.URLField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiouser',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiouser',
            name='radiourl',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiouser',
            name='tag',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
