# Generated by Django 4.1.3 on 2022-12-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kekw', '0004_remove_radiouser_radios_radiouser_img_radiouser_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='img',
        ),
        migrations.RemoveField(
            model_name='radiouser',
            name='img',
        ),
    ]
