# Generated by Django 4.1.3 on 2022-12-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kekw', '0005_remove_radio_img_remove_radiouser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiouser',
            name='tag',
            field=models.CharField(max_length=200),
        ),
    ]
